plugins {
    id "com.android.application"
}

android {
    namespace = "br.com.hunterafarm"
    compileSdk = 36

    defaultConfig {
        applicationId = "br.com.hunterafarm"
        minSdk = 24
        targetSdk = 36
        versionCode = 2
        versionName = "0.1.1-beta"

    }

    buildTypes {
        release {
            minifyEnabled = true
            shrinkResources = true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.activity:activity:1.13.0"
    implementation "androidx.webkit:webkit:1.17.0"

    testImplementation "junit:junit:4.13.2"
}
